### ISSUE TITLE
Important Dates for White Hats

### ISSUE THREAD

**Issue by JM532** [egetche/CompSystemsSecProject#2]
Researching the important dates important to white Hats

**Comment by NateOtting** [comment]
added important dates using our sources and citing's.

**Comment by NateOtting** [comment]
added more important dates based on the release of important sites and tools for white hat hackers.

**Comment by NateOtting** [comment]
I believe this is enough information for the report and will make a good slide in our presentation. perhaps I will add more dates relating to password cracking for our project.
